---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: config-map-create-reader
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kube-system
  name: config-map-create-reader
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "create", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:serviceaccount:kube-system:config-map-create-reader
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: config-map-create-reader
  namespace: kube-system
roleRef:
  kind: Role
  name: config-map-create-reader
  apiGroup: rbac.authorization.k8s.io