apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: talos-wifi
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: talos-wifi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: talos-wifi
      annotations:
        config.linkerd.io/shutdown-grace-period: 2s
    spec:
      hostNetwork: true
      serviceAccountName: config-map-create-reader
      containers:
      - image: registry.gitlab.centerionware.com/public-projects/talos-wifi:82b1638b
        metadata:
          annotations:
            config.linkerd.io/shutdown-grace-period: 2s
        name: talos-wifi
        volumeMounts:
          - name: task-pv-storage-dev
            mountPath: /dev
          - name: task-pv-storage-sys
            mountPath: /sys
          - name: task-pv-storage-proc
            mountPath: /proc
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_TIME"]
      volumes:
        - name: task-pv-storage-dev
          hostPath:
            path: /dev
            type: Directory
        - name: task-pv-storage-sys
          hostPath:
            path: /sys
            type: Directory
        - name: task-pv-storage-proc
          hostPath:
            path: /proc
            type: Directory